FROM ruby:3.0.0

MAINTAINER Dama Sukma <damasukmakd@gmail.com>

RUN apt-get update -qq && apt-get install -y \
    build-essential \ 
    nodejs \
    libpq-dev

RUN bundle config --global frozen 1

RUN mkdir -p /app
WORKDIR /app

COPY Gemfile Gemfile.lock /app/

EXPOSE 3000

RUN bundle install
CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
